name=PicoHA
version=0.0.1
author=Michał Leśniewski
maintainer=Michał Leśniewski <mlesniew@gmail.com>
sentence=Home Assistant MQTT integration helper
paragraph=A library to easily connect your ESP projects to Home Assistant using MQTT.
category=Communication
url=https://github.com/mlesniew/PicoHA
architectures=esp8266,esp32
depends=PicoMQTT, PicoSlugify, PicoString
