[env]
framework = arduino
lib_ldf_mode = deep
lib_deps = symlink://../../
monitor_speed = 115200
upload_speed = 921600

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:nodemcuv2-stdfunction]
platform = espressif8266
board = nodemcuv2
build_flags = -DPICOCALLBACK_USE_STD_FUNCTION

[env:esp32dev-stdfunction]
platform = espressif32
board = esp32dev
build_flags = -DPICOCALLBACK_USE_STD_FUNCTION
